import { Inter } from 'next/font/google';
import CursorGlow from '@/components/ui/CursorGlow/CursorGlow';
import Navbar from '@/components/layout/Navbar/Navbar';
import './globals.css';

const inter = Inter({
   variable: '--font-inter',
   subsets: ['latin'],
});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" className={inter.variable}>
         <body>
            <CursorGlow />
            <Navbar />
            {/* Relative position just for z-index, to appear above CursorGlow*/}
            <div style={{ position: 'relative', zIndex: 2 }}>{children}</div>
         </body>
      </html>
   );
}
